import { Link } from 'react-router-dom';
import { ArrowLeft, Shield, Lock, FileText, Users, AlertTriangle, Scale, MessageSquare, Baby } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-dark-950">
      {/* Header */}
      <div className="sticky top-0 z-40 bg-dark-900/95 backdrop-blur-md border-b border-dark-800">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link
            to="/feed"
            className="inline-flex items-center gap-2 text-dark-400 hover:text-primary-400 transition-colors"
          >
            <ArrowLeft size={18} />
            Back to Feed
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-8 pb-24">
        {/* Title */}
        <div className="text-center mb-12">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">
            Terms, Policies & Guidelines
          </h1>
          <p className="text-dark-400 max-w-2xl mx-auto">
            Telugu Anonymous Confession Platform - Legal Documentation
          </p>
          <p className="text-dark-500 text-sm mt-2">
            Last Updated: December 2024
          </p>
        </div>

        {/* Quick Navigation */}
        <nav className="card mb-8">
          <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
            <FileText size={20} className="text-primary-400" />
            Quick Navigation
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            <a href="#terms" className="text-primary-400 hover:underline text-sm py-1">1. Terms & Conditions</a>
            <a href="#privacy" className="text-primary-400 hover:underline text-sm py-1">2. Privacy Policy</a>
            <a href="#content" className="text-primary-400 hover:underline text-sm py-1">3. Content Policy</a>
            <a href="#community" className="text-primary-400 hover:underline text-sm py-1">4. Community Guidelines</a>
            <a href="#age" className="text-primary-400 hover:underline text-sm py-1">5. Age Restriction & Child Safety</a>
            <a href="#legal" className="text-primary-400 hover:underline text-sm py-1">6. Government & Legal Compliance</a>
            <a href="#disclaimer" className="text-primary-400 hover:underline text-sm py-1">7. Disclaimer & Limitation of Liability</a>
            <a href="#grievance" className="text-primary-400 hover:underline text-sm py-1">8. Grievance Redressal Policy</a>
          </div>
        </nav>

        {/* Terms & Conditions */}
        <section id="terms" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-primary-600/20 flex items-center justify-center">
              <FileText size={20} className="text-primary-400" />
            </div>
            <h2 className="text-2xl font-bold">1. Terms & Conditions</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <p>
              Users must agree to these Terms before using the platform. By using our service, you confirm that you are at least 18 years old and that all information you provide (including age) is true and lawful. We act solely as an intermediary: we do not create or endorse user content. All posts, comments, reactions and images are generated by users. We have no editorial control and expressly disclaim any liability for user-generated content. Users are responsible for their own posts, opinions, and any consequences of using the platform.
            </p>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">User Responsibilities</h3>
              <ul className="list-disc list-inside space-y-2 text-sm">
                <li>You must comply with all applicable laws and these Terms.</li>
                <li>You agree not to post illegal, obscene, hateful, harassing, defamatory or infringing content.</li>
                <li>Do not impersonate others or reveal personal data that could identify any person.</li>
                <li>You are solely responsible for the content you create and share.</li>
              </ul>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Age Requirement</h3>
              <p className="text-sm">
                You confirm you are 18 or older. Accounts of minors or users misrepresenting their age will be suspended. We do not encourage use by anyone under 18. If a user under 18 is identified, we will immediately remove their content and terminate access.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Platform Rights</h3>
              <p className="text-sm">
                We reserve the right to remove or disable access to any content and to suspend or terminate any account that violates these Terms or applicable law. This includes content that is illegal or that we deem inappropriate. We may do so without prior notice. We also reserve the right to change or discontinue any feature at any time.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Intermediary Role</h3>
              <p className="text-sm">
                Under Section 79 of India's Information Technology Act, we claim "safe harbor" protection - meaning we are not liable for third-party content so long as we follow due diligence. We are a neutral intermediary and do not endorse any user's statements or submissions.
              </p>
            </div>
          </div>
        </section>

        {/* Privacy Policy */}
        <section id="privacy" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-green-600/20 flex items-center justify-center">
              <Lock size={20} className="text-green-400" />
            </div>
            <h2 className="text-2xl font-bold">2. Privacy Policy</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <p>
              We value your anonymity and privacy. We collect only minimal data necessary to operate the platform. No real-name identity is required. Typical data collected may include only a username and email (or authentication token) and technical log data (IP address, device info) needed to provide the service. Passwords are securely hashed; platform administrators cannot read your password. We do not sell or share personal data to third parties.
            </p>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Data Collection</h3>
              <p className="text-sm">
                We may use cookies or similar technologies to maintain sessions and improve service. We limit tracking to the essentials (e.g., a session cookie). We do not place ads or track your browsing beyond our platform.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Data Use</h3>
              <p className="text-sm">
                Your data is used only to run and improve the service (e.g. account management, detecting abuse). We do not use your data for unrelated purposes. We will store your data for no longer than needed (generally not beyond 180 days from account deletion). You may request deletion of your account and all associated data at any time.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Anonymity & Security</h3>
              <p className="text-sm">
                We do not require or verify your identity. Any data that could identify you is kept private. We do not log the content of your communications (only metadata like timestamps and IP for abuse prevention). Sensitive data (passwords) are hashed; we employ standard security measures.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Law Enforcement</h3>
              <p className="text-sm">
                We comply with legal obligations in India. If required by law or by a valid court/government request, we may disclose user data and content. We will take all legal measures to protect user anonymity, but we will not obstruct lawful investigations.
              </p>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Children's Privacy</h3>
              <p className="text-sm">
                Our platform is intended only for adults. We do not knowingly collect data from anyone under 18.
              </p>
            </div>
          </div>
        </section>

        {/* Content Policy */}
        <section id="content" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-red-600/20 flex items-center justify-center">
              <Shield size={20} className="text-red-400" />
            </div>
            <h2 className="text-2xl font-bold">3. Content Policy</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <p>
              All content on the platform is user-generated. We strictly prohibit the following content:
            </p>

            <div className="bg-red-900/20 border border-red-700/50 rounded-xl p-4">
              <h3 className="font-semibold text-red-300 mb-3">Strictly Prohibited Content</h3>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Child Sexual Content</strong> - Absolutely banned, illegal under IT Act Section 67B</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Pornography Involving Minors</strong> - Zero tolerance policy</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Rape, Sexual Violence and Threats</strong> - Including glorification or encouragement</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Harassment, Hate Speech, Extremism</strong> - Targeting individuals or groups</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Defamation and Privacy Violations</strong> - Including doxxing</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Non-Consensual/Intimate Content</strong> - Revenge porn or similar</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Illegal Content</strong> - Any content violating Indian law</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Obscene/Explicit Material</strong> - Graphic pornographic images/videos</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 mt-1">-</span>
                  <span><strong>Other Criminal Content</strong> - Including fraud, scams, terrorism</span>
                </li>
              </ul>
            </div>

            <p className="text-sm text-dark-400 italic">
              We reserve the right to immediately remove any violating content and suspend accounts without prior notice.
            </p>
          </div>
        </section>

        {/* Community Guidelines */}
        <section id="community" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-blue-600/20 flex items-center justify-center">
              <Users size={20} className="text-blue-400" />
            </div>
            <h2 className="text-2xl font-bold">4. Community Guidelines</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <div className="grid gap-4">
              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Respect Others</h3>
                <p className="text-sm">Be courteous, no harassment or hate speech. Treat fellow community members with dignity.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Keep It Anonymous</h3>
                <p className="text-sm">Don't identify others or share private info. This platform is built on anonymity - protect it.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Stay on Topic</h3>
                <p className="text-sm">Use relevant tags for your confessions. This helps others find content they're interested in.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">No Spam or Promotion</h3>
                <p className="text-sm">Don't post promotional content, advertisements, or spam. Keep the platform genuine.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Follow the Rules</h3>
                <p className="text-sm">Report violations when you see them. Help us maintain a safe community for everyone.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Age Restriction & Child Safety */}
        <section id="age" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-orange-600/20 flex items-center justify-center">
              <Baby size={20} className="text-orange-400" />
            </div>
            <h2 className="text-2xl font-bold">5. Age Restriction & Child Safety Policy</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <div className="bg-orange-900/20 border border-orange-700/50 rounded-xl p-4">
              <h3 className="font-semibold text-orange-300 mb-3">Strict Age Requirements</h3>
              <ul className="space-y-2 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-orange-400 font-bold">18+</span>
                  <span>Minimum age requirement to use this platform</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-red-400 font-bold">ZERO</span>
                  <span>Tolerance for underage sexual content</span>
                </li>
              </ul>
            </div>

            <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
              <h3 className="font-semibold text-dark-100 mb-3">Child Safety Measures</h3>
              <ul className="list-disc list-inside space-y-2 text-sm">
                <li>Users under 18 will be removed immediately upon identification</li>
                <li>All content from underage users will be deleted</li>
                <li>We actively cooperate with authorities for child safety matters</li>
                <li>Reports involving minors are prioritized and handled within 24 hours</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Government & Legal Compliance */}
        <section id="legal" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-purple-600/20 flex items-center justify-center">
              <Scale size={20} className="text-purple-400" />
            </div>
            <h2 className="text-2xl font-bold">6. Government & Legal Compliance Policy</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <div className="grid gap-4">
              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Indian Law Compliance</h3>
                <p className="text-sm">We comply with all applicable Indian laws including the Information Technology Act, 2000 and IT Rules, 2021.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Grievance Officer</h3>
                <p className="text-sm">We have appointed a Grievance Officer as required by law to address user complaints and government requests.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Response Timeline</h3>
                <p className="text-sm">We respond to valid legal requests from government authorities within 72 hours as mandated by law.</p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Governing Law</h3>
                <p className="text-sm">This platform is governed by the laws of India. Any disputes will be subject to the exclusive jurisdiction of Indian courts.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Disclaimer & Limitation of Liability */}
        <section id="disclaimer" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-yellow-600/20 flex items-center justify-center">
              <AlertTriangle size={20} className="text-yellow-400" />
            </div>
            <h2 className="text-2xl font-bold">7. Disclaimer & Limitation of Liability</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <div className="bg-yellow-900/20 border border-yellow-700/50 rounded-xl p-4">
              <h3 className="font-semibold text-yellow-300 mb-3">Important Disclaimers</h3>
              <ul className="space-y-3 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">-</span>
                  <span><strong>No Endorsement:</strong> We do not endorse, verify, or take responsibility for any user-generated content.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">-</span>
                  <span><strong>Not Professional Advice:</strong> Content on this platform should not be considered medical, legal, psychological, or any other professional advice.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">-</span>
                  <span><strong>As-Is Service:</strong> The platform is provided "as is" without warranties of any kind, express or implied.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">-</span>
                  <span><strong>No Liability for Distress:</strong> We are not liable for any emotional distress, harm, or consequences resulting from using this platform or its content.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-yellow-400 mt-1">-</span>
                  <span><strong>Use at Your Own Risk:</strong> You use this platform entirely at your own risk and discretion.</span>
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* Grievance Redressal Policy */}
        <section id="grievance" className="card mb-6 scroll-mt-20">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-full bg-cyan-600/20 flex items-center justify-center">
              <MessageSquare size={20} className="text-cyan-400" />
            </div>
            <h2 className="text-2xl font-bold">8. Content Takedown & Grievance Redressal Policy</h2>
          </div>

          <div className="space-y-4 text-dark-300 leading-relaxed">
            <p>
              We are committed to addressing user concerns promptly and fairly. Here's how our grievance redressal process works:
            </p>

            <div className="grid gap-4">
              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">How to Report</h3>
                <p className="text-sm">
                  Contact our Grievance Officer via email with your complaint. Include details of the content/issue and any supporting information.
                </p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Acknowledgement</h3>
                <p className="text-sm">
                  We will acknowledge receipt of your complaint within <strong>24 hours</strong>.
                </p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Resolution Timeline</h3>
                <p className="text-sm">
                  Standard complaints will be resolved within <strong>15 days</strong> of receipt.
                </p>
              </div>

              <div className="bg-cyan-900/20 border border-cyan-700/50 rounded-xl p-4">
                <h3 className="font-semibold text-cyan-300 mb-2">Priority Cases</h3>
                <p className="text-sm">
                  Serious issues including child safety content, imminent threats, or violence will be handled within <strong>24 hours</strong>.
                </p>
              </div>

              <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
                <h3 className="font-semibold text-dark-100 mb-2">Appeals</h3>
                <p className="text-sm">
                  If you disagree with our decision, you may file an appeal within <strong>7 days</strong> of receiving our response.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Footer Note */}
        <div className="text-center text-dark-500 text-sm mt-8 pb-8">
          <p>
            By using Telugu Anonymous Confession Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and Policies.
          </p>
          <p className="mt-4">
            For any questions or concerns, please contact our support team.
          </p>
        </div>

        {/* Back to top */}
        <div className="text-center">
          <button
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            className="btn-secondary"
          >
            Back to Top
          </button>
        </div>
      </div>
    </div>
  );
}
